spring.application.name=lb-apigw

# When and where to route the requests
spring.cloud.gateway.routes[0].id=e-commerce-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**, /users/**
spring.cloud.gateway.routes[0].uri=lb://e-commerce-service

# ideally product, user and payment services should be separate routes as they are supposed to be separate microservices
#spring.cloud.gateway.routes[1].id=userservice
#spring.cloud.gateway.routes[1].predicates[0]=Path=/users**, /login**
#spring.cloud.gateway.routes[1].uri=lb://userservice

## OR condition in a single route
#spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**, /users/**
## AND condition in a single route
#spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**
#spring.cloud.gateway.routes[0].predicates[1]=Method=POST
#spring.cloud.gateway.routes[0].predicates[2]=Header=Authorization, Bearer.*

# in production the eureka service discovery server url will be different which you'll need to set here
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

#logging.level.*=trace
management.endpoints.web.exposure.include=*